project_id = "ccomlhxhigqqmoexpmyy"

[functions.delete-user]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.reset-all-verification]
verify_jwt = false

[functions.cleanup-expired-servers]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false