version: '3.8'

services:
  skyserver-web:
    container_name: skyserver_website
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: "https://ccomlhxhigqqmoexpmyy.supabase.co"
        VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjb21saHhoaWdxcW1vZXhwbXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MjMzMzcsImV4cCI6MjA4NTk5OTMzN30.pmX6v2EJZARQHY7tDx13GidW50YnXQ-KeiGNE5NcwtM"
    ports:
      - "7012:7012"
    restart: always
