version: '3.8'

services:
  skyserver-web:
    container_name: skyserver_website
    build:
      context: .
      dockerfile: Dockerfile
    # Maps port 7012 on host to port 80 in container
    ports:
      - "7012:80"
    restart: always
